AllCops:
  TargetRubyVersion: 3
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'

Layout/LineLength:
  IgnoredPatterns: [ '^#' ]
  Max: 150

Layout/SpaceAroundOperators:
  EnforcedStyleForExponentOperator: space

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/tasks/**/*'
    - 'config/environments/*.rb'
    - 'config/initializers/*.rb'
    - 'config/routes.rb'

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

#Layout/HashAlignment:
#  EnforcedColonStyle:

Layout/BeginEndAlignment:
  EnforcedStyleAlignWith: begin

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'db/**/*'

Style/Documentation:
  Enabled: false

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/MethodLength:
  Exclude:
    - 'db/**/*'
  Max: 15

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/DoubleNegation:
  Enabled: false

GlobalVars:
  AllowedVariables:
    - $redis
    - $geo_ip
